version: "3"
services:
  tomcat_redis:
    container_name: tomcat_redis
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./docker/redis/data:/data"
    environment:
      TZ: Asia/Tokyo
    networks:
      - back
networks:
  back: